AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Sample Template for creating an Amazon RDS DB instance.
Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'Password {{parameters.metadata.name}} database access'
      GenerateSecretString:
          SecretStringTemplate:  '{"username": "dbadmin"}'
          GenerateStringKey: 'password'
          PasswordLength: 16
          ExcludeCharacters: '"@/\'
  PostgresSampleDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: "{{parameters.metadata.name}}-instance"
      DBName: "{{parameters.metadata.name}}"
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: "{{parameters.spec.storageSize}}"
      StorageType: gp3
      Engine: postgres
      EngineVersion: "{{parameters.spec.version}}"
      MasterUsername: !Join ['', ['\{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['\{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:password}}' ]]